blank_issues_enabled: false
contact_links:
  - name: 👀 Discord Support
    url: https://discord.com/invite/VQhkKMq8dF
    about: |
      The best location to turn to for quick support is our discord server.
      If you have a question or need help, drop by and we can work through your issue together!
      
